(function(g){var window=this;var $Ca=function(a,b){return g.Xb(a,b)},y6=function(a){g.Om(a,"zx",g.zb());
return a},z6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Rm(a.o,b,c)},aDa=function(a,b){var c=[];
g.Dk(b,function(a){try{var b=g.rD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.qD(b)&&c.push(a):c.push(a)},a);
return c},bDa=function(a,b){var c=aDa(a,b);
(0,g.C)(c,function(a){g.rD.prototype.remove.call(this,a)},a)},cDa=function(a){if(a.Ed){if(a.Ed.locationOverrideToken)return{locationOverrideToken:a.Ed.locationOverrideToken};
if(null!=a.Ed.latitudeE7&&null!=a.Ed.longitudeE7)return{latitudeE7:a.Ed.latitudeE7,longitudeE7:a.Ed.longitudeE7}}return null},dDa=function(a,b,c,d){var e=new g.Fm(null,void 0);
a&&g.Gm(e,a);b&&g.Hm(e,b);c&&g.Im(e,c);d&&g.Jm(e,d);return e},eDa=function(a){g.gG[a]&&(a=g.gG[a],(0,g.C)(a,function(a){g.eG[a]&&delete g.eG[a]}),a.length=0)},fDa=function(a){var b=g.dG();
if(b)if(b.clear(a),a)eDa(a);else for(var c in g.gG)eDa(c)},A6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.zm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gDa(this,a.capabilities||""),hDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},gDa=function(a,b){a.capabilities.clear();
(0,g.Qd)(b.split(","),g.Fa($Ca,iDa)).forEach(function(b){a.capabilities.add(b)})},hDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},B6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},C6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kDa=function(a){return new B6(a)},lDa=function(a){return g.za(a)?(0,g.I)(a,kDa):[]},D6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},E6=function(a){return g.za(a)?"["+(0,g.I)(a,D6).join(",")+"]":"null"},F6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},mDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},G6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},H6=function(a,b){return g.La(a,function(a){return C6(a,b)})},nDa=function(){var a=(0,g.cH)();
a&&bDa(a,a.o.Zd(!0))},I6=function(){var a=g.fH("yt-remote-connected-devices")||[];
g.gb(a);return a},oDa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},pDa=function(a){g.eH("yt-remote-connected-devices",a,86400)},K6=function(){if(J6)return J6;
var a=g.fH("yt-remote-device-id");a||(a=F6(),g.eH("yt-remote-device-id",a,31536E3));for(var b=I6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return J6=d},L6=function(){var a=I6(),b=K6();
g.Pa(a,b);g.hH()&&g.kb(a,b);a=oDa(a);if(g.Qa(a))try{g.PG("remote_sid")}catch(c){}else try{g.OG("remote_sid",a.join(","),-1)}catch(c){}},qDa=function(){return g.fH("yt-remote-session-browser-channel")},rDa=function(){return g.fH("yt-remote-local-screens")||[]},sDa=function(){g.eH("yt-remote-lounge-token-expiration",!0,86400)},tDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(rDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.nm)(c,function(a){return!g.Pa(b,a)})&&sDa();
g.eH("yt-remote-local-screens",a,31536E3)},uDa=function(a,b){g.eH("yt-remote-session-browser-channel",a);
g.eH("yt-remote-session-screen-id",b);var c=I6(),d=K6();g.Pa(c,d)||c.push(d);pDa(c);L6()},M6=function(a){a||(g.gH("yt-remote-session-screen-id"),g.gH("yt-remote-session-video-id"));
L6();a=I6();g.Ua(a,K6());pDa(a)},vDa=function(){if(!N6){var a=g.CD();
a&&(N6=new g.lD(a))}return N6?!!N6.get("yt-remote-use-staging-server"):!1},wDa=function(){var a=window.document.createElement("a");
g.ed(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Db(a)},xDa=function(a,b){var c=g.Id("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.fd(c,g.ge("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},yDa=function(){var a=wDa(),b=window.document.getElementById(a),c=b&&g.pF(b,"loaded");
c||b&&!c||(b=xDa(a,function(){g.pF(b,"loaded")||(g.oF(b,"loaded","true"),g.kG(a),g.kE(g.Fa(fDa,a),0))}))},O6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},zDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},P6=function(a){a.length?ADa(a.shift(),function(){P6(a)}):Q6()},BDa=function(a){return"chrome-extension://"+a+R6},ADa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},S6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Q6=function(){var a=zDa();
a&&a(!1,"No cast extension found")},T6=function(){if(CDa){var a=2,b=zDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ADa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Q6,c)}},DDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(T6(),a({command:"cast.sender.init"}))},EDa=function(){T6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);P6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+R6,"//www.gstatic.com/eureka/clank"+R6])},U6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.ud=b;this.D=(0,g.A)(this.lK,this);this.o=!1;this.A=0;this.B=this.Fa=null;this.C=[]},V6=function(){},W6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Vm(this);this.A=new g.Bg;this.A.setInterval(250)},GDa=function(a,b,c){a.Vj=1;
a.wh=y6(b.clone());a.cj=c;a.D=!0;FDa(a,null)},X6=function(a,b,c,d,e){a.Vj=1;
a.wh=y6(b.clone());a.cj=null;a.D=c;e&&(a.sE=!1);FDa(a,d)},FDa=function(a,b){a.Mk=(0,g.G)();
Y6(a);a.Th=a.wh.clone();z6(a.Th,"t",a.F);a.fn=0;a.Sc=a.o.Xr(a.o.Sm()?b:null);0<a.Ms&&(a.eq=new g.gl((0,g.A)(a.KF,a,a.Sc),a.Ms));a.Y.W(a.Sc,"readystatechange",a.JV);var c=a.Ai?g.fc(a.Ai):{};a.cj?(a.Sq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Sc.send(a.Th,a.Sq,a.cj,c)):(a.Sq="GET",a.sE&&!g.Ed&&(c.Connection="close"),a.Sc.send(a.Th,a.Sq,null,c));a.o.Df(1)},JDa=function(a,b,c){for(var d=!0;!a.ki&&a.fn<c.length;){var e=HDa(a,c);
if(e==Z6){4==b&&(a.xh=4,$6(15),d=!1);break}else if(e==IDa){a.xh=4;$6(16);d=!1;break}else a7(a,e)}4==b&&0==c.length&&(a.xh=1,$6(17),d=!1);a.Jf=a.Jf&&d;d||(b7(a),c7(a))},HDa=function(a,b){var c=a.fn,d=b.indexOf("\n",c);
if(-1==d)return Z6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return IDa;d+=1;if(d+c>b.length)return Z6;var e=b.substr(d,c);a.fn=d+c;return e},LDa=function(a,b){a.Mk=(0,g.G)();
Y6(a);var c=b?window.location.hostname:"";a.Th=a.wh.clone();g.Om(a.Th,"DOMAIN",c);g.Om(a.Th,"t",a.F);try{a.Kf=new window.ActiveXObject("htmlfile")}catch(n){b7(a);a.xh=7;$6(22);c7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in d7)k=d7[l];else if(l in KDa)k=d7[l]=KDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=d7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.gd(g.zc("b/12014412"),d);a.Kf.open();a.Kf.write(g.Zc(c));a.Kf.close();a.Kf.parentWindow.m=(0,g.A)(a.QU,a);a.Kf.parentWindow.d=(0,g.A)(a.BD,a,!0);a.Kf.parentWindow.rpcClose=(0,g.A)(a.BD,a,!1);c=a.Kf.createElement("DIV");a.Kf.parentWindow.document.body.appendChild(c);d=g.Oc(a.Th.toString());d=g.sb(g.Lc(d));d=g.gd(g.zc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Zc(d);
a.o.Df(1)},Y6=function(a){a.tw=(0,g.G)()+a.C;
MDa(a,a.C)},MDa=function(a,b){if(null!=a.dl)throw Error("WatchDog timer not null");
a.dl=e7((0,g.A)(a.hV,a),b)},f7=function(a){a.dl&&(g.x.clearTimeout(a.dl),a.dl=null)},c7=function(a){a.o.Kz()||a.ki||a.o.Pp(a)},b7=function(a){f7(a);
g.gf(a.eq);a.eq=null;a.A.stop();g.an(a.Y);if(a.Sc){var b=a.Sc;a.Sc=null;b.abort();b.dispose()}a.Kf&&(a.Kf=null)},a7=function(a,b){try{a.o.tD(a,b),a.o.Df(4)}catch(c){}},ODa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;NDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){ODa(a,b,c,d,f)},f)})}},NDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{g7(d),c(!0)}catch(e){}};
d.onerror=function(){try{g7(d),c(!1)}catch(e){}};
d.onabort=function(){try{g7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{g7(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},g7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},PDa=function(a){this.o=a;
this.A=new V6},QDa=function(a){var b=h7(a.o,a.ql,"/mail/images/cleardot.gif");
y6(b);ODa(b.toString(),5E3,(0,g.A)(a.xJ,a),3,2E3);a.Df(1)},j7=function(a){var b=a.o.J;
if(null!=b)$6(5),b?($6(11),i7(a.o,a,!1)):($6(12),i7(a.o,a,!0));else if(a.Ae=new W6(a,void 0,void 0,void 0),a.Ae.Ai=a.Ks,b=a.o,b=h7(b,b.Sm()?a.Ql:null,a.Ls),$6(5),!g.Cd||g.vc(10))z6(b,"TYPE","xmlhttp"),X6(a.Ae,b,!1,a.Ql,!1);else{z6(b,"TYPE","html");var c=a.Ae;a=!!a.Ql;c.Vj=3;c.wh=y6(b.clone());LDa(c,a)}},k7=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new V6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},RDa=function(a,b){this.o=a;
this.map=b;this.context=null},SDa=function(a){g.jf.call(this,"statevent",a)},TDa=function(a,b){g.jf.call(this,"timingevent",a);
this.size=b},UDa=function(a){g.jf.call(this,"serverreachability",a)},XDa=function(a){VDa(a);
if(3==a.o){var b=a.Cm++,c=a.to.clone();g.Om(c,"SID",a.B);g.Om(c,"RID",b);g.Om(c,"TYPE","terminate");l7(a,c);b=new W6(a,a.B,b,void 0);b.Vj=2;b.wh=y6(c.clone());(new window.Image).src=b.wh;b.Mk=(0,g.G)();Y6(b)}WDa(a)},YDa=function(a){a.SJ(1,0);
a.to=h7(a,null,a.Js);m7(a)},VDa=function(a){a.lh&&(a.lh.abort(),a.lh=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.Ag&&(g.x.clearTimeout(a.Ag),a.Ag=null);n7(a);a.fe&&(a.fe.cancel(),a.fe=null);a.oh&&(g.x.clearTimeout(a.oh),a.oh=null)},ZDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new RDa(a.DQ++,b));2!=a.o&&3!=a.o||m7(a)},m7=function(a){a.fe||a.oh||(a.oh=e7((0,g.A)(a.zD,a),0),a.Jj=0)},aEa=function(a,b){if(1==a.o){if(!b){a.Cm=Math.floor(1E5*Math.random());
var c=a.Cm++,d=new W6(a,"",c,void 0);d.Ai=null;var e=o7(a),f=a.to.clone();g.Om(f,"RID",c);g.Om(f,"CVER","1");l7(a,f);GDa(d,f,e);a.fe=d;a.o=2}}else 3==a.o&&(b?$Da(a,b):0==a.A.length||a.fe||$Da(a))},$Da=function(a,b){if(b)if(6<a.mi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Cm-1;var d=o7(a)}else c=b.G,d=b.cj;else c=a.Cm++,d=o7(a);var e=a.to.clone();g.Om(e,"SID",a.B);g.Om(e,"RID",c);g.Om(e,"AID",a.jk);l7(a,e);c=new W6(a,a.B,c,a.Jj+1);c.Ai=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.fe=c;GDa(c,e,d)},l7=function(a,b){if(a.td){var c=a.td.qz();
c&&g.Mb(c,function(a,c){g.Om(b,c,a)})}},o7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.mi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.mi?e:f-d;try{g.Mb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},bEa=function(a){a.wc||a.Ag||(a.G=1,a.Ag=e7((0,g.A)(a.yD,a),0),a.wj=0)},p7=function(a){if(a.wc||a.Ag||3<=a.wj)return!1;
a.G++;a.Ag=e7((0,g.A)(a.yD,a),cEa(a,a.wj));a.wj++;return!0},i7=function(a,b,c){a.Rq=c;
a.Zf=b.Mg;a.F||YDa(a)},n7=function(a){null!=a.oi&&(g.x.clearTimeout(a.oi),a.oi=null)},cEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},q7=function(a,b){if(2==b||9==b){var c=null;
a.td&&(c=null);var d=(0,g.A)(a.EW,a);c||(c=new g.Fm("//www.google.com/images/cleardot.gif"),y6(c));NDa(c.toString(),1E4,d)}else $6(2);dEa(a,b)},dEa=function(a,b){a.o=0;
a.td&&a.td.ky(b);WDa(a);VDa(a)},WDa=function(a){a.o=0;
a.Zf=-1;if(a.td)if(0==a.C.length&&0==a.A.length)a.td.Lr();else{g.Xa(a.C);var b=g.Xa(a.A);a.C.length=0;a.A.length=0;a.td.Lr(b)}},h7=function(a,b,c){var d=g.Pm(c);
if(""!=d.A)b&&g.Hm(d,b+"."+d.A),g.Im(d,d.D);else{var e=window.location;d=dDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Cl&&g.Mb(a.Cl,function(a,b){g.Om(d,b,a)});
g.Om(d,"VER",a.mi);l7(a,d);return d},e7=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},$6=function(a){r7.dispatchEvent(new SDa(r7,a))},eEa=function(){},fEa=function(a,b){this.action=a;
this.params=b||{}},s7=function(a,b){g.M.call(this);
this.o=new g.ku(this.HU,0,this);g.N(this,this.o);this.ud=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},t7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.kD;this.A=new s7(this.oX,this);this.o=this.bb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},gEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Rq,sessionId:a.o.B,arrayId:a.o.jk}},hEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&aEa(a.o),XDa(a.o));a.H=0},u7=function(a){return!!a.o&&3==a.o.o},iEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},v7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Rg(a)||"";b&&(this.port=":"+b);this.domain=g.Qg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cb(a,"10.0")&&(this.A=!1))},w7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.bh(c+b,{})},x7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Ad:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.BE(b,a)},mEa=function(){var a=jEa;
kEa();y7.push(a);lEa(y7)},z7=function(a,b){kEa();
var c=y7,d=nEa(a,String(b));g.Qa(c)?oEa(d):(lEa(c),(0,g.C)(c,function(a){a(d)}))},kEa=function(){y7||(y7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",y7,void 0))},oEa=function(a){var b=(A7+1)%50;
A7=b;B7[b]=a;C7||(C7=49==b)},lEa=function(a){var b=B7;
if(b[0]){var c=A7,d=C7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
B7=Array(50);A7=-1;C7=!1}},nEa=function(a,b){var c=((0,g.G)()-pEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},D7=function(a){g.WF.call(this);
this.G=a;this.o=[]},qEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},rEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Qd)(a.o,function(a){return!!G6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=qEa(a,b[d])||c;return c},sEa=function(a,b){var c=a.o.length;
a.o=(0,g.Qd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},E7=function(a,b,c,d){g.WF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Fa=window.NaN},G7=function(a){D7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;F7(this);this.info("Initializing with "+E6(this.o))},tEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=w7(a.B,"/pairing/get_lounge_token_batch");
x7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.yK,a),(0,g.A)(a.xK,a))}},F7=function(a){var b=lDa(rDa());
b=(0,g.Qd)(b,function(a){return!a.uuid});
return rEa(a,b)},H7=function(a,b){tDa((0,g.I)(a.o,jDa));
b&&sDa()},J7=function(a,b){g.WF.call(this);
this.F=b;var c=g.fH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;I7("Initialized with "+g.Ig(this.o))},uEa=function(a,b,c){var d=w7(a.D,"/pairing/get_screen_availability");
x7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},K7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.o))var c=!1;
else{c=g.Ub(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(I7("Updated online screens: "+g.Ig(a.o)),a.o=b,a.V("screenChange"));vEa(a)},L7=function(a){(0,window.isNaN)(a.B)||g.mE(a.B);
a.B=g.kE((0,g.A)(a.Hv,a),0<a.C&&a.C<(0,g.G)()?2E4:1E4)},I7=function(a){z7("OnlineScreenService",a)},wEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},vEa=function(a){a=g.Ub(g.Nb(a.o,function(a){return a}));
g.gb(a);a.length?g.eH("yt-remote-online-screen-ids",a.join(","),60):g.gH("yt-remote-online-screen-ids")},M7=function(a){D7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};xEa(this)},zEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.se();if(k=(c?H6(k,c):null)||H6(k,b)){k.uuid=b;var l=N7(a,k);uEa(a.A,l,function(a){e(a?l:null)})}else c?yEa(a,c,(0,g.A)(function(a){var f=N7(this,new B6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));uEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},AEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},yEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.BE(w7(a.F,"/pairing/get_lounge_token_batch"),e)},BEa=function(a){a.o=a.B.se();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+E6(a.o))},xEa=function(a){O7(a);
a.B=new G7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.NK,a));BEa(a);a.C=lDa(g.fH("yt-remote-automatic-screen-cache")||[]);O7(a);a.info("Initializing automatic screens: "+E6(a.C));a.A=new J7(a.F,(0,g.A)(a.se,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},N7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=H6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.eH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,jDa)));O7(a);a.D[b.uuid]=b.id;g.eH("yt-remote-device-id-map",a.D,31536E3);return b},O7=function(a){a.D=g.fH("yt-remote-device-id-map")||{}},P7=function(a,b,c){g.WF.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},Q7=function(a,b){z7(a.M,b)},R7=function(a,b){P7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.uX,this);this.D=(0,g.A)(this.tV,this);this.C=g.kE((0,g.A)(function(){CEa(this,null)},this),12E4)},DEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){Q7(this,"Failed to send message: getMdxSessionStatus.")},a)):Q7(a,"Sending yt message without session: "+g.Ig(b))},CEa=function(a,b){g.mE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Qp,a),d=(0,g.A)(a.ye,a);a.Cz(b,c,d,5)}}else a.ye(Error("Waiting for session status timed out."))},S7=function(a,b,c){P7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.xX,this);this.o=g.z},EEa=function(a){a.o=a.J.RF(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Qp(a)},a),(0,g.A)(function(a){this.o=g.z;
this.ye(a)},a))},FEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}vDa()&&(b.env_useStageMdx=1);return g.$g(b)},T7=function(a,b){P7.call(this,a,b,"ManualSession");
this.o=g.kE((0,g.A)(this.lk,this,null),150)},U7=function(a,b,c,d){g.WF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.ST,this)},GEa=function(a,b){return b?g.La(a.B,function(a){return C6(b,a.label)},a):null},V7=function(a){z7("Controller",a)},jEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},W7=function(a){return a.D||!!a.B.length||!!a.o},X7=function(a,b,c){b!=a.o&&(g.gf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.wD,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.lk(null)):a.V("yt-remote-cast2-session-change",null))},HEa=function(a){var b=a.A.QF(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&C6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=GEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},NEa=function(a,b,c,d,e,f,k){IEa()?JEa(b,e,f,k)&&(Z7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?KEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?KEa(a,c):($7("Failed to load cast API: "+d),a8(!1),Z7(!1),g.gH("yt-remote-cast-available"),g.gH("yt-remote-cast-receiver"),LEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):yDa():S6("CriOS")?DDa():S6("Android")&&S6("Chrome/")&&window.navigator.presentation?EDa():window.chrome&&window.navigator.presentation&&!S6("Edge")?(T6(),P6(MEa.map(BDa))):Q6())):Y7("Cannot initialize because not running Chrome")},LEa=function(){Y7("dispose");
var a=b8();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);OEa(!1);g.iG(c8);c8.length=0},d8=function(){return!!g.fH("yt-remote-cast-installed")},PEa=function(){var a=g.fH("yt-remote-cast-receiver");
return a?a.friendlyName:null},QEa=function(){Y7("clearCurrentReceiver");
g.gH("yt-remote-cast-receiver")},REa=function(){return d8()?b8()?b8().getCastSession():($7("getCastSelector: Cast is not initialized."),null):($7("getCastSelector: Cast API is not installed!"),null)},f8=function(){d8()?b8()?e8()?(Y7("Requesting cast selector."),b8().requestSession()):(Y7("Wait for cast API to be ready to request the session."),c8.push(g.hG("yt-remote-cast2-api-ready",f8))):$7("requestCastSelector: Cast is not initialized."):$7("requestCastSelector: Cast API is not installed!")},g8=
function(a,b){e8()?b8().setConnectedScreenStatus(a,b):$7("setConnectedScreenStatus called before ready.")},IEa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.EJ||a},SEa=function(a,b){b8().init(a,b)},JEa=function(a,b,c,d){var e=!1;
b8()||(a=new U7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.eH("yt-remote-cast-available",a);g.lG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){Y7("onReceiverSelected: "+a.friendlyName);
g.eH("yt-remote-cast-receiver",a);g.lG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){Y7("onReceiverResumed: "+a.friendlyName);
g.eH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){Y7("onSessionChange: "+D6(a));
a||g.gH("yt-remote-cast-receiver");g.lG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
Y7("cloudview.createSingleton_: "+e);return e},b8=function(){return g.y("yt.mdx.remote.cloudview.instance_")},KEa=function(a,b){a8(!0);
Z7(!1);SEa(a,function(a){a?(OEa(!0),g.kG("yt-remote-cast2-api-ready")):($7("Failed to initialize cast API."),a8(!1),g.gH("yt-remote-cast-available"),g.gH("yt-remote-cast-receiver"),LEa());b(a)})},Y7=function(a){z7("cloudview",a)},$7=function(a){z7("cloudview",a)},a8=function(a){Y7("setCastInstalled_ "+a);
g.eH("yt-remote-cast-installed",a)},e8=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},OEa=function(a){Y7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Z7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},h8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.dg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},i8=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.dg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.G)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},j8=function(a){return a.ob()?((0,g.G)()-a.G)/1E3:0},k8=function(a,b){a.H=b;
a.G=(0,g.G)()},l8=function(a){switch(a.o){case 1:case 1081:return((0,g.G)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},m8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&i8(a)},n8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.gc(a.A);b.hasPrevious=a.dg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},p8=function(a,b){g.WF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.BC;this.B=this.A=null;this.J=(0,g.A)(this.nR,this);this.G=(0,g.A)(this.Fm,this);this.H=(0,g.A)(this.mR,this);this.K=(0,g.A)(this.zR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Bw,this),TEa(this))):c=3;0!=c&&(b?this.Bw(c):g.kE((0,g.A)(function(){this.Bw(c)},this),0));
var d=REa();d&&o8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},q8=function(a){return new h8(a.C.getPlayerContextData())},TEa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.NT,a),this))},a)},UEa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},r8=function(a,b){50>a.D.Fc()&&g.DC(a.D,b)},t8=function(a,b,c){var d=q8(a);
k8(d,c);-1E3!=d.o&&(d.o=b);s8(a,d)},u8=function(a,b,c){a.C.sendMessage(b,c)},s8=function(a,b){UEa(a);
a.C.setPlayerContextData(n8(b));TEa(a)},o8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Fm(null));
a.B=b;a.B&&(z7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Fm(a.B.media[0]))},VEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=q8(a);b.contentId!=d.videoId&&z7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;k8(d,a.A.getEstimatedTime());s8(a,d)}else z7("CP","No cast media video. Ignoring state update.")},v8=function(a,b,c){return(0,g.A)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),u8(this,b,c))},a)},w8=function(a,b,c){g.WF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.fb=this.o=null;this.sa=a;this.T.push(g.FF(window,"beforeunload",(0,g.A)(this.pK,this)));this.A=[];this.fb=new h8;this.ba=b.id;this.o=WEa(this,c);this.o.subscribe("handlerOpened",this.rR,this);this.o.subscribe("handlerClosed",this.oR,this);this.o.subscribe("handlerError",this.pR,this);this.o.subscribe("handlerMessage",this.qR,this);iEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.fb.videoId;g.hH()&&g.eH("yt-remote-session-video-id",a)},this)},x8=function(a){z7("conn",a)},WEa=function(a,b){return new t7(w7(a.sa,"/bc"),b)},y8=function(a,b){a.V("proxyStateChange",b)},XEa=function(a){a.D=g.kE((0,g.A)(function(){x8("Connecting timeout");
this.F(1)},a),2E4)},z8=function(a){g.mE(a.D);
a.D=window.NaN},A8=function(a){g.mE(a.M);
a.M=window.NaN},YEa=function(a){B8(a);
a.L=g.kE((0,g.A)(function(){C8(this,"getNowPlaying")},a),2E4)},B8=function(a){g.mE(a.L);
a.L=window.NaN},$Ea=function(a,b){b&&(z8(a),A8(a));
b==(u7(a.o)&&(0,window.isNaN)(a.D))?b&&(y8(a,1),C8(a,"getSubtitlesTrack")):b?(a.Z()&&a.fb.reset(),y8(a,1),C8(a,"getNowPlaying"),ZEa(a)):a.F(1)},aFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.$b(b.params)?a.fb.A=null:a.fb.A=b.params,a.V("remotePlayerChange"))},bFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;m8(a.fb,c,d);a.V("remoteQueueChange")},dFa=function(a,b){b.params=b.params||{};
bFa(a,b);cFa(a,b);a.V("autoplayDismissed")},cFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
k8(a.fb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.fb.o&&(c=-1E3);a.fb.o=c;c=Number(b.params.loadedTime);a.fb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.fb.J=(0,window.isNaN)(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.fb.o?YEa(a):B8(a);
a.V("remotePlayerChange")},eFa=function(a,b){if(-1E3!=a.fb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);k8(a.fb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},fFa=function(a,b){var c="true"==b.params.muted;
a.fb.volume=(0,window.parseInt)(b.params.volume,10);a.fb.muted=c;a.V("remotePlayerChange")},gFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},hFa=function(a,b){var c="true"==b.params.hasNext;
a.fb.dg="true"==b.params.hasPrevious;a.fb.hasNext=c;a.V("previousNextChange")},ZEa=function(a){g.mE(a.K);
a.K=g.kE((0,g.A)(a.F,a,1),864E5)},C8=function(a,b,c){c?x8("Sending: action="+b+", params="+g.Ig(c)):x8("Sending: action="+b);
a.o.sendMessage(b,c)},D8=function(a){D7.call(this,"ScreenServiceProxy");
this.jd=a;this.A=[];this.A.push(this.jd.$_s("screenChange",(0,g.A)(this.sX,this)));this.A.push(this.jd.$_s("onlineScreenChange",(0,g.A)(this.oT,this)))},mFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.eE("MDX_CONFIG")||b;nDa();L6();E8||(E8=new v7(b?b.loungeApiHost:void 0),vDa()&&(E8.o="/api/loungedev"));F8||(F8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",F8,void 0));iFa();var c=G8();if(!c){var d=new M7(E8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=G8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);NEa(a,d,function(a){a?H8()&&g8(H8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.lG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),I8("Initializing: "+g.Ig(b)),J8.push(g.hG("yt-remote-cast2-availability-change",function(){g.lG("yt-remote-receiver-availability-change")})),J8.push(g.hG("yt-remote-cast2-receiver-selected",function(){K8(null);
g.lG("yt-remote-auto-connect","cast-selector-receiver")})),J8.push(g.hG("yt-remote-cast2-receiver-resumed",function(){g.lG("yt-remote-receiver-resumed","cast-selector-receiver")})),J8.push(g.hG("yt-remote-cast2-session-change",jFa)),J8.push(g.hG("yt-remote-connection-change",function(a){a?g8(H8(),"YouTube TV"):L8()||(g8(null,null),QEa())})),a=M8(),b.isAuto&&(a.id+="#dial"),g.bG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),I8(" -- with channel params: "+
g.Ig(a)),kFa(a),c.start(),H8()||lFa())},oFa=function(){var a=nFa();
d8()&&g.fH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},nFa=function(){var a=G8().jd.$_gos();
var b=N8();b&&O8()&&(G6(a,b)||a.push(b));return mDa(a)},P8=function(){var a=pFa();
!a&&d8()&&PEa()&&(a={key:"cast-selector-receiver",name:PEa()});return a},pFa=function(){var a=nFa(),b=N8();
b||(b=L8());return g.La(a,function(a){return b&&C6(b,a.key)?!0:!1})},N8=function(){var a=H8();
if(!a)return null;var b=G8().se();return H6(b,a)},jFa=function(a){I8("remote.onCastSessionChange_: "+D6(a));
if(a){var b=N8();b&&b.id==a.id?g8(b.id,"YouTube TV"):(b&&Q8(),R8(a,1))}else O8()&&Q8()},Q8=function(){e8()?b8().stopSession():$7("stopSession called before API ready.");
var a=O8();a&&(a.disconnect(1),S8(null))},T8=function(){var a=O8();
return!!a&&3!=a.getProxyState()},I8=function(a){z7("remote",a)},G8=function(){if(!U8){var a=g.y("yt.mdx.remote.screenService_");
U8=a?new D8(a):null}return U8},H8=function(){return g.y("yt.mdx.remote.currentScreenId_")},qFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},rFa=function(){return g.y("yt.mdx.remote.connectData_")},K8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},O8=function(){return g.y("yt.mdx.remote.connection_")},S8=function(a){var b=O8();
K8(null);a||qFa("");g.ua("yt.mdx.remote.connection_",a,void 0);F8&&((0,g.C)(F8,function(b){b(a)}),F8.length=0);
b&&!a?g.lG("yt-remote-connection-change",!1):!b&&a&&g.lG("yt-remote-connection-change",!0)},L8=function(){var a=g.hH();
if(!a)return null;var b=G8().se();return H6(b,a)},R8=function(a,b){N8()&&N8();
qFa(a.id);var c=new w8(E8,a,M8());c.connect(b,rFa());c.subscribe("beforeDisconnect",function(a){g.lG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){O8()&&S8(null)});
S8(c)},lFa=function(){var a=L8();
a?(I8("Resume connection to: "+D6(a)),R8(a,0)):(M6(),QEa(),I8("Skipping connecting because no session screen found."))},iFa=function(){var a=M8();
if(g.$b(a)){a=K6();var b=g.fH("yt-remote-session-name")||"",c=g.fH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},M8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},kFa=function(a){a?(g.eH("yt-remote-session-app",a.app),g.eH("yt-remote-session-name",a.name)):(g.gH("yt-remote-session-app"),g.gH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},V8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.TF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.GS);this.B.R(b,"captionschanged",this.lR);this.B.R(b,"captionssettingschanged",this.eF);this.B.R(b,"videoplayerreset",this.Rp);this.B.R(b,"mdxautoplaycancel",this.wJ);this.T=this.B.R(b,"onVolumeChange",this.fD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.sD,this);c.subscribe("remotePlayerChange",this.Im,this);c.subscribe("remoteQueueChange",this.Rp,this);c.subscribe("autoplayUpNext",this.QC,
this);c.subscribe("previousNextChange",this.pD,this);c.subscribe("nowAutoplaying",this.hD,this);c.subscribe("autoplayDismissed",this.PC,this);this.suggestion=null;this.J=new g.vQ(64);this.C=new g.ku(this.ZE,500,this);g.N(this,this.C);this.D=new g.ku(this.aF,1E3,this);g.N(this,this.D);this.L=new U6(this.TW,0,this);g.N(this,this.L);this.F={};this.M=new g.ku(this.AF,1E3,this);g.N(this,this.M);this.K=new g.gl(this.kP,1E3,this);g.N(this,this.K);this.O=g.z;this.eF();this.Rp();this.Im()},W8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},sFa=function(a){W8(a,0);
a.C.stop();X8(a,new g.vQ(64))},Z8=function(a,b){if(Y8(a)&&!a.G){var c=null;
b&&(c={style:a.A.Ui()},g.ic(c,b));a.o.NE(a.A.getVideoData(1).videoId,c);a.F=q8(a.o).A}},$8=function(a,b){var c=a.A.kg();
if(c){var d=c.qe();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.ek;f=cDa(f);var n=q8(c);l=l||0;var p={videoId:k,currentIndex:l};m8(n,k,l);g.u(b)&&(k8(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ig(f));u8(c,"setPlaylist",p);e||s8(c,n);X8(a,new g.vQ(1))},tFa=function(a,b){if(b){var c=a.A.zc("captions","tracklist",{vA:1});
c&&c.length?(a.A.Td("captions","track",b),a.G=!1):(a.A.vk("captions"),a.G=!0)}else a.A.Td("captions","track",{})},Y8=function(a){return q8(a.o).videoId==a.A.getVideoData(1).videoId},X8=function(a,b){a.D.stop();
var c=a.J;if(!g.AQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.xU(a.A,d);a.J=b;uFa(a.H,c,b)}},a9=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.Vqa()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.A=new g.nV(this,250);g.N(this,this.A);this.C=a;this.R(a,"presentingplayerstatechange",this.D);vFa(this,g.uU(a))},vFa=function(a,b){if(3==a.C.Qa()){var c={RECEIVER_NAME:a.C.zc("remote","currentReceiver").name};
c=g.X(b,128)?g.s0("Error on $RECEIVER_NAME",c):b.ob()||g.X(b,4)?g.s0("Playing on $RECEIVER_NAME",c):g.s0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.A.show()}else a.A.hide()},b9=function(a,b){g.yZ.call(this,"Play on",0,a,b);
this.A=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},c9=function(a){g.UU.call(this,a);
this.B={key:F6(),name:"This computer"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.vQ(64);this.J=0;if(!g.YN(g.Y(this.o))){a=this.o;var b=g.XH(a);b&&(b=b.mp())&&(b=new b9(a,b),g.N(this,b));b=new a9(a);g.N(this,b);g.NU(a,b.element,4)}},uFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.FQ(c,b))},d9=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)Q8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.kg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ac(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ek,index:Math.max(a.o.yB(),0),currentTime:0==f?void 0:f};(d=cDa(d))&&(c.locationInfo=d);d=c}else d=null;I8("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?(K8(d||null),e8()?b8().setLaunchParams(d||null):
$7("setLaunchParams called before ready.")):!d&&T8()&&H8()==b.key?g.lG("yt-remote-connection-change",!0):(Q8(),K8(d||null),d=G8().se(),(d=H6(d,b.key))&&R8(d,1))}},KDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},d7={"'":"\\'"},wFa={},iDa={IY:"atp",n3:"ska",C2:"que",L1:"mus",h3:"sus",Q_:"dsp"};
A6.prototype.ao=function(){var a=new A6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var N6,J6="",R6=O6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",CDa=O6("loadCastFramework")||O6("loadCastApplicationFramework"),MEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(U6,g.M);g.h=U6.prototype;g.h.kK=function(a){this.C=arguments;this.o=!1;this.Fa?this.B=(0,g.G)()+this.ud:this.Fa=g.Cg(this.D,this.ud)};
g.h.stop=function(){this.Fa&&(g.Dg(this.Fa),this.Fa=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();U6.ea.X.call(this)};
g.h.lK=function(){this.B?(this.Fa=g.Cg(this.D,this.B-(0,g.G)()),this.B=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};V6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
V6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=W6.prototype;g.h.Ai=null;g.h.Jf=!1;g.h.dl=null;g.h.tw=null;g.h.Mk=null;g.h.Vj=null;g.h.wh=null;g.h.Th=null;g.h.cj=null;g.h.Sc=null;g.h.fn=0;g.h.Kf=null;g.h.Sq=null;g.h.xh=null;g.h.Rl=-1;g.h.sE=!0;g.h.ki=!1;g.h.Ms=0;g.h.eq=null;var IDa={},Z6={};g.h=W6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.JV=function(a){a=a.target;var b=this.eq;b&&3==g.wx(a)?b.Tj():this.KF(a)};
g.h.KF=function(a){try{if(a==this.Sc)a:{var b=g.wx(this.Sc),c=this.Sc.A,d=this.Sc.getStatus();if(g.Cd&&!g.vc(10)||g.Ed&&!g.uc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.lf&&!g.Ax(this.Sc))break a;this.ki||4!=b||7==c||(8==c||0>=d?this.o.Df(3):this.o.Df(2));f7(this);var e=this.Sc.getStatus();this.Rl=e;var f=g.Ax(this.Sc);(this.Jf=200==e)?(4==b&&b7(this),this.D?(JDa(this,b,f),g.lf&&this.Jf&&3==b&&(this.Y.W(this.A,"tick",this.FV),this.A.start())):a7(this,f),this.Jf&&!this.ki&&(4==b?this.o.Pp(this):
(this.Jf=!1,Y6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.xh=3,$6(13)):(this.xh=0,$6(14)),b7(this),c7(this))}}catch(k){this.Sc&&g.Ax(this.Sc)}finally{}};
g.h.FV=function(){var a=g.wx(this.Sc),b=g.Ax(this.Sc);this.fn<b.length&&(f7(this),JDa(this,a,b),this.Jf&&4!=a&&Y6(this))};
g.h.QU=function(a){e7((0,g.A)(this.PU,this,a),0)};
g.h.PU=function(a){this.ki||(f7(this),a7(this,a),Y6(this))};
g.h.BD=function(a){e7((0,g.A)(this.OU,this,a),0)};
g.h.OU=function(a){this.ki||(b7(this),this.Jf=a,this.o.Pp(this),this.o.Df(4))};
g.h.cancel=function(){this.ki=!0;b7(this)};
g.h.hV=function(){this.dl=null;var a=(0,g.G)();0<=a-this.tw?(2!=this.Vj&&this.o.Df(3),b7(this),this.xh=2,$6(18),c7(this)):MDa(this,this.tw-a)};g.h=PDa.prototype;g.h.Ks=null;g.h.Ae=null;g.h.fq=!1;g.h.Lz=null;g.h.po=null;g.h.Rt=null;g.h.Ls=null;g.h.Se=null;g.h.Mg=-1;g.h.Ql=null;g.h.ql=null;g.h.connect=function(a){this.Ls=a;a=h7(this.o,null,this.Ls);$6(3);this.Lz=(0,g.G)();var b=this.o.H;null!=b?(this.Ql=b[0],(this.ql=b[1])?(this.Se=1,QDa(this)):(this.Se=2,j7(this))):(z6(a,"MODE","init"),this.Ae=new W6(this,void 0,void 0,void 0),this.Ae.Ai=this.Ks,X6(this.Ae,a,!1,null,!0),this.Se=0)};
g.h.xJ=function(a){if(a)this.Se=2,j7(this);else{$6(4);var b=this.o;b.Zf=b.lh.Mg;q7(b,9)}a&&this.Df(2)};
g.h.Xr=function(a){return this.o.Xr(a)};
g.h.abort=function(){this.Ae&&(this.Ae.cancel(),this.Ae=null);this.Mg=-1};
g.h.Kz=function(){return!1};
g.h.tD=function(a,b){this.Mg=a.Rl;if(0==this.Se)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Mg;q7(c,2);return}this.Ql=c[0];this.ql=c[1]}else c=this.o,c.Zf=this.Mg,q7(c,2);else if(2==this.Se)if(this.fq)$6(7),this.Rt=(0,g.G)();else if("11111"==b){if($6(6),this.fq=!0,this.po=(0,g.G)(),c=this.po-this.Lz,!g.Cd||g.vc(10)||500>c)this.Mg=200,this.Ae.cancel(),$6(12),i7(this.o,this,!0)}else $6(8),this.po=this.Rt=(0,g.G)(),this.fq=!1};
g.h.Pp=function(){this.Mg=this.Ae.Rl;if(this.Ae.Jf)0==this.Se?this.ql?(this.Se=1,QDa(this)):(this.Se=2,j7(this)):2==this.Se&&((!g.Cd||g.vc(10)?!this.fq:200>this.Rt-this.po)?($6(11),i7(this.o,this,!1)):($6(12),i7(this.o,this,!0)));else{0==this.Se?$6(9):2==this.Se&&$6(10);var a=this.o;a.Zf=this.Mg;q7(a,2)}};
g.h.Sm=function(){return this.o.Sm()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Df=function(a){this.o.Df(a)};g.h=k7.prototype;g.h.Cl=null;g.h.fe=null;g.h.wc=null;g.h.Js=null;g.h.to=null;g.h.Yx=null;g.h.Go=null;g.h.Cm=0;g.h.DQ=0;g.h.td=null;g.h.oh=null;g.h.Ag=null;g.h.oi=null;g.h.lh=null;g.h.Rq=null;g.h.jk=-1;g.h.JA=-1;g.h.Zf=-1;g.h.Jj=0;g.h.wj=0;g.h.mi=8;var r7=new g.Mf;g.B(SDa,g.jf);g.B(TDa,g.jf);g.B(UDa,g.jf);g.h=k7.prototype;g.h.connect=function(a,b,c,d,e){$6(0);this.Js=b;this.Cl=c||{};d&&g.u(e)&&(this.Cl.OSID=d,this.Cl.OAID=e);this.F?(e7((0,g.A)(this.zy,this,a),100),YDa(this)):this.zy(a)};
g.h.zy=function(a){this.lh=new PDa(this);this.lh.Ks=null;this.lh.A=this.D;this.lh.connect(a)};
g.h.Kz=function(){return 0==this.o};
g.h.zD=function(a){this.oh=null;aEa(this,a)};
g.h.yD=function(){this.Ag=null;this.wc=new W6(this,this.B,"rpc",this.G);this.wc.Ai=null;this.wc.Ms=0;var a=this.Yx.clone();g.Om(a,"RID","rpc");g.Om(a,"SID",this.B);g.Om(a,"CI",this.Rq?"0":"1");g.Om(a,"AID",this.jk);l7(this,a);if(!g.Cd||g.vc(10))g.Om(a,"TYPE","xmlhttp"),X6(this.wc,a,!0,this.Go,!1);else{g.Om(a,"TYPE","html");var b=this.wc,c=!!this.Go;b.Vj=3;b.wh=y6(a.clone());LDa(b,c)}};
g.h.tD=function(a,b){if(0!=this.o&&(this.wc==a||this.fe==a))if(this.Zf=a.Rl,this.fe==a&&3==this.o)if(7<this.mi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Ag){if(this.wc)if(this.wc.Mk+3E3<this.fe.Mk)n7(this),this.wc.cancel(),this.wc=null;else break a;p7(this);$6(19)}}else this.JA=c[1],0<this.JA-this.jk&&37500>c[2]&&this.Rq&&0==this.wj&&!this.oi&&(this.oi=e7((0,g.A)(this.gR,this),6E3));else q7(this,11)}else b!=wFa.LZ.o&&q7(this,11);else if(this.wc==a&&
n7(this),!g.E(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.jk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Go=e[2],e=e[3],null!=e?this.mi=e:this.mi=6,this.o=3,this.td&&this.td.my(),this.Yx=h7(this,this.Sm()?this.Go:null,this.Js),bEa(this)):"stop"==e[0]&&q7(this,7):3==this.o&&("stop"==e[0]?q7(this,7):"noop"!=e[0]&&this.td&&this.td.ly(e),this.wj=0)}}};
g.h.gR=function(){null!=this.oi&&(this.oi=null,this.wc.cancel(),this.wc=null,p7(this),$6(20))};
g.h.Pp=function(a){if(this.wc==a){n7(this);this.wc=null;var b=2}else if(this.fe==a)this.fe=null,b=1;else return;this.Zf=a.Rl;if(0!=this.o)if(a.Jf)1==b?(b=(0,g.G)()-a.Mk,r7.dispatchEvent(new TDa(r7,a.cj?a.cj.length:0,b,this.Jj)),m7(this),this.C.length=0):bEa(this);else{var c=a.xh,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.fe||this.oh||1==this.o||2<=this.Jj?d=!1:(this.oh=e7((0,g.A)(this.zD,this,a),cEa(this,this.Jj)),this.Jj++,d=!0);d=!(d||2==b&&p7(this))}if(d)switch(c){case 1:q7(this,5);
break;case 4:q7(this,10);break;case 3:q7(this,6);break;case 7:q7(this,12);break;default:q7(this,2)}}};
g.h.SJ=function(a){if(!g.Pa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.EW=function(a){a?$6(2):($6(1),dEa(this,8))};
g.h.Xr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.qx;a.H=!1;return a};
g.h.isActive=function(){return!!this.td&&this.td.isActive(this)};
g.h.Df=function(a){r7.dispatchEvent(new UDa(r7,a))};
g.h.Sm=function(){return!(!g.Cd||g.vc(10))};
g.h=eEa.prototype;g.h.my=function(){};
g.h.ly=function(){};
g.h.ky=function(){};
g.h.Lr=function(){};
g.h.qz=function(){return{}};
g.h.isActive=function(){return!0};g.B(s7,g.M);g.h=s7.prototype;g.h.HU=function(){this.ud=Math.min(3E5,2*this.ud);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.ud+15E3*Math.random();g.nu(this.o,a);this.A=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.ud=5E3};g.B(t7,eEa);g.h=t7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Yd=function(a){return this.B.Yd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.gf(this.B),hEa(this),g.gf(this.A),this.A=null)};
g.h.ma=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new k7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.td=null);d.td=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.jk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ic(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):u7(this)&&ZDa(this.o,c)};
g.h.my=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)ZDa(this.o,a[b])}this.V("handlerOpened")};
g.h.ky=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Lr=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.qz=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.ic(a,this.D);return a};
g.h.ly=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),XDa(this.o)):this.V("handlerMessage",new fEa(a[0],a[1]))};
g.h.oX=function(){this.A.isActive();var a=this.o,b=0;a.wc&&b++;a.fe&&b++;0!=b||this.connect(this.D,this.C)};v7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
v7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
v7.prototype.D=function(a){a(Error("request timed out"))};var pEa=(0,g.G)(),y7=null,B7=Array(50),A7=-1,C7=!1;g.B(D7,g.WF);D7.prototype.se=function(){return this.o};
D7.prototype.contains=function(a){return!!G6(this.o,a)};
D7.prototype.get=function(a){return a?H6(this.o,a):null};
D7.prototype.info=function(a){z7(this.G,a)};g.B(E7,g.WF);var xFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=E7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Fa)&&this.PF()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Fa)||(g.mE(this.Fa),this.Fa=window.NaN)};
g.h.X=function(){this.stop();E7.ea.X.call(this)};
g.h.PF=function(){this.Fa=window.NaN;this.o=g.BE(w7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.qX,this),onError:(0,g.A)(this.pX,this),Ad:(0,g.A)(this.rX,this)})};
g.h.qX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new B6(c))};
g.h.pX=function(a){this.o=null;a.status&&404==a.status?this.A>=xFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=xFa[this.A],this.Fa=g.kE((0,g.A)(this.PF,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.rX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(G7,D7);g.h=G7.prototype;g.h.start=function(){F7(this)&&this.V("screenChange");!g.fH("yt-remote-lounge-token-expiration")&&tEa(this);g.mE(this.A);this.A=g.kE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){F7(this);qEa(this,a);H7(this,!1);this.V("screenChange");b(a);a.token||tEa(this)};
g.h.remove=function(a,b){var c=F7(this);sEa(this,a)&&(H7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Lq=function(a,b,c,d){var e=F7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,H7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.mE(this.A);G7.ea.X.call(this)};
g.h.yK=function(a){F7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}H7(this,!b);b&&z7(this.G,"Missed "+b+" lounge tokens.")};
g.h.xK=function(a){z7(this.G,"Requesting lounge tokens failed: "+a)};g.B(J7,g.WF);g.h=J7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.fH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.G)()-144E5<a?0:a)?L7(this):(this.C=(0,g.G)()+3E5,g.eH("yt-remote-fast-check-period",this.C),this.Hv())};
g.h.isEmpty=function(){return g.$b(this.o)};
g.h.update=function(){I7("Updating availability on schedule.");var a=this.F(),b=g.Nb(this.o,function(b,d){return b&&!!H6(a,d)},this);
K7(this,b)};
g.h.X=function(){g.mE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);J7.ea.X.call(this)};
g.h.Hv=function(){g.mE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=wEa(this);if(g.Qb(a)){var b=w7(this.D,"/pairing/get_screen_availability");this.A=x7(this.D,b,{lounge_token:g.Ub(a).join(",")},(0,g.A)(this.pU,this,a),(0,g.A)(this.oU,this))}else K7(this,{}),L7(this)};
g.h.pU=function(a,b){this.A=null;var c=g.Ub(wEa(this));if(g.jb(c,g.Ub(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;K7(this,d);L7(this)}else this.hc("Changing Screen set during request."),this.Hv()};
g.h.oU=function(a){this.hc("Screen availability failed: "+a);this.A=null;L7(this)};
g.h.hc=function(a){z7("OnlineScreenService",a)};g.B(M7,D7);g.h=M7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Lq=function(a,b,c,d){this.B.contains(a)?this.B.Lq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,z7(this.G,a),d(Error(a)))};
g.h.se=function(a){return a?this.o:g.Wa(this.o,(0,g.Qd)(this.C,function(a){return!this.contains(a)},this))};
g.h.QF=function(){return(0,g.Qd)(this.se(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.RF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new E7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.gf(f);d(N7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.gf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.tX=function(a,b,c,d){g.BE(w7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new B6(d.screen||{});if(!e.name||AEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);AEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(N7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Ad:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.gf(this.B);g.gf(this.A);M7.ea.X.call(this)};
g.h.NK=function(){BEa(this);this.V("screenChange");this.A.update()};
M7.prototype.dispose=M7.prototype.dispose;g.B(P7,g.WF);g.h=P7.prototype;g.h.Qp=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.ye=function(a){this.ma()||(a&&Q7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){z7(this.M,a)};
g.h.TF=function(){return null};
g.h.Nv=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){Q7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Nv("");P7.ea.X.call(this)};g.B(R7,P7);g.h=R7.prototype;g.h.Mv=function(a){if(this.o){if(this.o==a)return;Q7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);DEa(this)};
g.h.lk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.ye()},this),(0,g.A)(function(){this.ye(Error("Failed to stop receiver app."))},this)):this.ye(Error("Stopping cast device witout session."))};
g.h.Nv=g.z;g.h.X=function(){this.info("disposeInternal");g.mE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;R7.ea.X.call(this)};
g.h.tV=function(a,b){if(!this.ma())if(b){var c=g.kx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":CEa(this,c.screenId);break;default:Q7(this,"Unknown youtube message: "+d)}}else Q7(this,"Unable to parse message.")}else Q7(this,"No data in message.")};
g.h.Cz=function(a,b,c,d){zEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(Q7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.kE((0,g.A)(this.Cz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.TF=function(){return this.o};
g.h.uX=function(a){this.ma()||a||(Q7(this,"Cast session died."),this.ye())};g.B(S7,P7);g.h=S7.prototype;g.h.Mv=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.lk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.mE(this.F);this.C?this.C.stop((0,g.A)(this.ye,this,null),(0,g.A)(this.ye,this,"Failed to stop DIAL device.")):this.ye()};
g.h.X=function(){this.o();this.o=g.z;g.mE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;S7.ea.X.call(this)};
g.h.xX=function(a){this.ma()||a||(Q7(this,"DIAL session died."),this.o(),this.o=g.z,this.ye())};
g.h.Ft=function(a){this.K=F6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,FEa(this));a(b);EEa(this)}else this.G=(0,g.A)(function(){g.mE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,FEa(this));a(b);EEa(this)},this),this.F=g.kE((0,g.A)(function(){this.G()},this),100)};
g.h.cM=function(a,b,c){zEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Qp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Ft(b,c)},this),(0,g.A)(function(a){Q7(this,"Failed to get DIAL screen: "+a);
this.Ft(b,c)},this))};g.B(T7,P7);T7.prototype.stop=function(){this.ye()};
T7.prototype.Mv=g.z;T7.prototype.lk=function(){g.mE(this.o);this.o=window.NaN;var a=H6(this.J.se(),this.A.label);a?this.Qp(a):this.ye(Error("No such screen"))};
T7.prototype.X=function(){g.mE(this.o);this.o=window.NaN;T7.ea.X.call(this)};g.B(U7,g.WF);g.h=U7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.vD,this),(0,g.A)(this.XT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.RR,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ma()||(window.chrome.cast.addReceiverActionListener(this.C),mEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.SF,this)),this.B=HEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.V("yt-remote-cast2-availability-change",W7(this)),b(!0))},this),(0,g.A)(function(a){this.hc("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.kW=function(a,b){V7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)V7("Unsetting old screen status: "+this.o.A.friendlyName),X7(this,null)}if(a&&b){if(!this.o){c=H6(this.A.se(),a);if(!c){V7("setConnectedScreenStatus: Unknown screen.");return}var d=GEa(this,c);d||(V7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Ig(a))},this)));
V7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);X7(this,new T7(this.A,d),!0)}this.o.Nv(b)}else V7("setConnectedScreenStatus: no screen.")};
g.h.lW=function(a){this.ma()?this.hc("Setting connection data on disposed cast v2"):this.o?this.o.lk(a):this.hc("Setting connection data without a session")};
g.h.wX=function(){this.ma()?this.hc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),X7(this,null)):V7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.vD,this),(0,g.A)(this.tU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.SF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ua(g.y("yt.mdx.remote.debug.handlers_")||[],jEa);g.gf(this.o);U7.ea.X.call(this)};
g.h.hc=function(a){z7("Controller",a)};
g.h.wD=function(a,b){this.o==a&&(b||X7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.ST=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),V7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)V7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{V7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:X7(this,
new T7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:X7(this,new S7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:X7(this,new R7(this.A,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.RR=function(a){if(this.ma())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return V7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);X7(this,new S7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.cM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Ft,b))};
g.h.vD=function(a){if(!this.ma()){V7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)V7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),X7(this,new R7(this.A,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=H6(this.A.se(),c.label);
d&&C6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(V7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.gf(this.o),this.o=new R7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.wD,this,this.o)),this.o.lk(null));this.o.Mv(a)}}};
g.h.vX=function(){return this.o?this.o.TF():null};
g.h.tU=function(a){this.ma()||(this.hc("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&X7(this,null))};
g.h.XT=function(a){V7("Receiver availability updated: "+a);if(!this.ma()){var b=W7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;W7(this)!=b&&this.V("yt-remote-cast2-availability-change",W7(this))}};
g.h.SF=function(){this.ma()||(this.B=HEa(this),V7("Updating custom receivers: "+g.Ig(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.hc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",W7(this)))};
U7.prototype.setLaunchParams=U7.prototype.lW;U7.prototype.setConnectedScreenStatus=U7.prototype.kW;U7.prototype.stopSession=U7.prototype.wX;U7.prototype.getCastSession=U7.prototype.vX;U7.prototype.requestSession=U7.prototype.requestSession;U7.prototype.init=U7.prototype.init;U7.prototype.dispose=U7.prototype.dispose;var c8=[];g.h=h8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";i8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.dg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.ob=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+j8(this):this.J};
g.h.clone=function(){return new h8(n8(this))};g.B(p8,g.WF);g.h=p8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,v8(this,"play")):u8(this,"play"),t8(this,1,l8(q8(this))),this.V("remotePlayerChange")):r8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,v8(this,"pause")):u8(this,"pause"),t8(this,2,l8(q8(this))),this.V("remotePlayerChange")):r8(this,this.pause)};
g.h.OF=function(a){if(1==this.o){if(this.A){var b=q8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ob()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,v8(this,"seekTo",{newTime:a}))}else u8(this,"seekTo",{newTime:a});t8(this,3,a);this.V("remotePlayerChange")}else r8(this,g.Fa(this.OF,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,v8(this,"stopVideo")):u8(this,"stopVideo");var a=q8(this);a.index=-1;a.videoId="";i8(a);s8(this,a);this.V("remotePlayerChange")}else r8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=q8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){z7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){z7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);u8(this,"setVolume",e)}c.muted=b;c.volume=a;s8(this,c)}else r8(this,g.Fa(this.setVolume,a,b))};
g.h.NE=function(a,b){if(1==this.o){var c=q8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.ic(d,c.A));u8(this,"setSubtitlesTrack",d);s8(this,c)}else r8(this,g.Fa(this.NE,a,b))};
g.h.Aw=function(a,b){if(1==this.o){u8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jb.id});var c=q8(this);c.audioTrackId=b.Jb.id;s8(this,c)}else r8(this,g.Fa(this.Aw,a,b))};
g.h.NF=function(a,b){if(1==this.o){if(a&&b){var c=q8(this);m8(c,a,b);s8(this,c)}u8(this,"previous")}else r8(this,g.Fa(this.NF,a,b))};
g.h.MF=function(a,b){if(1==this.o){if(a&&b){var c=q8(this);m8(c,a,b);s8(this,c)}u8(this,"next")}else r8(this,g.Fa(this.MF,a,b))};
g.h.Sy=function(){1==this.o?u8(this,"dismissAutoplay"):r8(this,this.Sy)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}p8.ea.dispose.call(this)};
g.h.X=function(){UEa(this);this.C=null;this.D.clear();o8(this,null);p8.ea.X.call(this)};
g.h.Bw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.EC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.NT=function(a,b){this.V(a,b)};
g.h.nR=function(a){if(!a)this.Fm(null),o8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=q8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)z7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,s8(this,b)}};
g.h.Fm=function(a){z7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),VEa(this),this.V("remotePlayerChange")};
g.h.mR=function(a){a?(VEa(this),this.V("remotePlayerChange")):this.Fm(null)};
g.h.zR=function(){var a=REa();a&&o8(this,a)};
g.h.hc=function(a){z7("CP",a)};g.B(w8,g.WF);g.h=w8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=k||0;this.fb.state=3;k8(this.fb,m);this.C="UNSUPPORTED";x8("Connecting with setPlaylist and params: "+g.Ig(l));this.o.connect({method:"setPlaylist",
params:g.Ig(l)},a,qDa())}else x8("Connecting without params"),this.o.connect({},a,qDa());XEa(this)};
g.h.dispose=function(){this.ma()||(this.V("beforeDispose"),y8(this,3));w8.ea.dispose.call(this)};
g.h.X=function(){z8(this);B8(this);A8(this);g.mE(this.J);this.J=window.NaN;g.mE(this.K);this.K=window.NaN;this.B=null;g.GF(this.T);this.T.length=0;this.o.dispose();w8.ea.X.call(this);this.C=this.G=this.A=this.fb=this.o=null};
g.h.pK=function(){this.F(2)};
g.h.rR=function(){x8("Channel opened");this.O&&(this.O=!1,A8(this),this.M=g.kE((0,g.A)(function(){x8("Timing out waiting for a screen.");this.F(1)},this),15E3));
uDa(gEa(this.o),this.ba)};
g.h.oR=function(){x8("Channel closed");(0,window.isNaN)(this.D)?M6(!0):M6();this.dispose()};
g.h.pR=function(a){M6();(0,window.isNaN)(this.H())?(x8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,x8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),y8(this,2))};
g.h.qR=function(a){a.params?x8("Received: action="+a.action+", params="+g.Ig(a.params)):x8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.kx(a.params.devices);this.A=(0,g.I)(a,function(a){return new A6(a)});
a=!!g.La(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
$Ea(this,a);break;case "loungeScreenDisconnected":g.Va(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
$Ea(this,!1);break;case "remoteConnected":var b=new A6(g.kx(a.params.device));g.La(this.A,function(a){return b?a.id==b.id:!1})||g.Sa(this.A,b);
break;case "remoteDisconnected":b=new A6(g.kx(a.params.device));g.Va(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":bFa(this,a);break;case "nowPlaying":dFa(this,a);break;case "onStateChange":cFa(this,a);break;case "onAdStateChange":eFa(this,a);break;case "onVolumeChanged":fFa(this,a);break;case "onSubtitlesTrackChanged":aFa(this,a);break;case "nowAutoplaying":gFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":hFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:x8("Unrecognized action: "+a.action)}};
g.h.UV=function(){if(this.B){var a=this.B;this.B=null;this.fb.videoId!=a&&C8(this,"getNowPlaying")}};
w8.prototype.subscribe=w8.prototype.subscribe;w8.prototype.unsubscribeByKey=w8.prototype.Yd;w8.prototype.ia=function(){var a=3;this.ma()||(a=0,(0,window.isNaN)(this.H())?u7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
w8.prototype.getProxyState=w8.prototype.ia;w8.prototype.F=function(a){x8("Disconnecting with "+a);z8(this);this.V("beforeDisconnect",a);1==a&&M6();hEa(this.o,a);this.dispose()};
w8.prototype.disconnect=w8.prototype.F;w8.prototype.ha=function(){var a=this.fb;this.B&&(a=this.fb.clone(),m8(a,this.B,a.index));return n8(a)};
w8.prototype.getPlayerContextData=w8.prototype.ha;
w8.prototype.na=function(a){var b=new h8(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.B=b.videoId,g.mE(this.J),this.J=g.kE((0,g.A)(this.UV,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.o==b.o&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&l8(this.fb)==l8(b)&&g.Ig(this.fb.A)==g.Ig(b.A)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
w8.prototype.setPlayerContextData=w8.prototype.na;w8.prototype.Z=function(){var a=this.o.F.id,b=g.La(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
w8.prototype.getOtherConnectedRemoteId=w8.prototype.Z;w8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.G)():window.NaN};
w8.prototype.getReconnectTimeout=w8.prototype.H;w8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
w8.prototype.getAutoplayMode=w8.prototype.aa;w8.prototype.da=function(){return this.G||""};
w8.prototype.getAutoplayVideoId=w8.prototype.da;w8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.ou(a.o);a.start()}};
w8.prototype.reconnect=w8.prototype.va;w8.prototype.ka=function(a,b){C8(this,a,b);ZEa(this)};
w8.prototype.sendMessage=w8.prototype.ka;g.B(D8,D7);g.h=D8.prototype;g.h.se=function(a){return this.jd.$_gs(a)};
g.h.contains=function(a){return!!this.jd.$_c(a)};
g.h.get=function(a){return this.jd.$_g(a)};
g.h.start=function(){this.jd.$_st()};
g.h.add=function(a,b,c){this.jd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.jd.$_r(a,b,c)};
g.h.Lq=function(a,b,c,d){this.jd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.jd.$_ubk(this.A[a]);this.A.length=0;this.jd=null;D8.ea.X.call(this)};
g.h.sX=function(){this.V("screenChange")};
g.h.oT=function(){this.V("onlineScreenChange")};
M7.prototype.$_st=M7.prototype.start;M7.prototype.$_gspc=M7.prototype.tX;M7.prototype.$_gsppc=M7.prototype.RF;M7.prototype.$_c=M7.prototype.contains;M7.prototype.$_g=M7.prototype.get;M7.prototype.$_a=M7.prototype.add;M7.prototype.$_un=M7.prototype.Lq;M7.prototype.$_r=M7.prototype.remove;M7.prototype.$_gs=M7.prototype.se;M7.prototype.$_gos=M7.prototype.QF;M7.prototype.$_s=M7.prototype.subscribe;M7.prototype.$_ubk=M7.prototype.Yd;var E8=null,F8=null,U8=null,J8=[];g.t(V8,g.M);g.h=V8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.sD,this);this.o.unsubscribe("remotePlayerChange",this.Im,this);this.o.unsubscribe("remoteQueueChange",this.Rp,this);this.o.unsubscribe("autoplayUpNext",this.QC,this);this.o.unsubscribe("previousNextChange",this.pD,this);this.o.unsubscribe("nowAutoplaying",this.hD,this);this.o.unsubscribe("autoplayDismissed",this.PC,this);this.o=this.H=null};
g.h.RB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(Y8(this)){if(!q8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":q8(this.o).ob()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Tj(c[0],c[1]);break;case "control_subtitles_set_track":Z8(this,c[0]);break;case "control_set_audio_track":c=c[0],Y8(this)&&this.o.Aw(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();$8(this,0==c?void 0:c);break;case "control_seek":$8(this,c[0]);break;case "control_subtitles_set_track":Z8(this,c[0]);break;case "control_set_audio_track":c=c[0],Y8(this)&&this.o.Aw(this.A.getVideoData(1).videoId,c)}};
g.h.lR=function(a){this.L.kK(a)};
g.h.TW=function(a){this.RB("control_subtitles_set_track",g.$b(a)?null:a)};
g.h.eF=function(){var a=this.A.zc("captions","track");g.$b(a)||Z8(this,a)};
g.h.fD=function(a){if(Y8(this)){this.o.unsubscribe("remotePlayerChange",this.Im,this);var b=Math.round(a.volume);a=!!a.muted;var c=q8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Im,this)}};
g.h.GS=function(){g.$b(this.F)||tFa(this,this.F);this.G=!1};
g.h.sD=function(a,b){this.D.stop();2==b&&this.aF()};
g.h.Im=function(){if(Y8(this)){this.C.stop();var a=q8(this.o);switch(a.o){case 1081:case 1:X8(this,new g.vQ(8));this.ZE();break;case 1085:case 3:X8(this,new g.vQ(9));break;case 1083:case 0:X8(this,new g.vQ(2));this.K.stop();W8(this,this.A.getVideoData().lengthSeconds);break;case 1084:X8(this,new g.vQ(4));break;case 2:X8(this,new g.vQ(4));W8(this,l8(a));break;case -1:X8(this,new g.vQ(64));break;case -1E3:X8(this,new g.vQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
q8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,tFa(this,a));a=q8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.AF()}else sFa(this)};
g.h.pD=function(){this.A.V("mdxpreviousnextchange")};
g.h.Rp=function(){Y8(this)||sFa(this)};
g.h.wJ=function(){this.o.Sy()};
g.h.QC=function(a){a&&(a=g.BE("/watch_queue_ajax",{method:"GET",dd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.TU,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.TU=function(a,b){var c=new g.oP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.hD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.PC=function(){this.A.V("mdxautoplaycanceled")};
g.h.kP=function(a,b){-1==q8(this.o).o?$8(this,a):b&&this.o.OF(a)};
g.h.AF=function(){if(Y8(this)){var a=q8(this.o);this.B.Ha(this.T);a.muted?this.A.mute():this.A.lg();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.fD)}};
g.h.ZE=function(){this.C.stop();if(!this.o.ma()){var a=q8(this.o);a.ob()&&X8(this,new g.vQ(8));W8(this,l8(a));this.C.start()}};
g.h.aF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(a9,g.W);a9.prototype.D=function(a){vFa(this,a.state)};g.t(b9,g.yZ);b9.prototype.L=function(){var a=this.A.zc("remote","receivers");a&&1<a.length&&!this.A.zc("remote","quickCast")?(this.J=g.lb(a,this.F,this),g.zZ(this,(0,g.I)(a,this.F)),a=this.A.zc("remote","currentReceiver"),this.Cf(this.F(a)),this.enable(!0)):this.enable(!1)};
b9.prototype.F=function(a){return a.key};
b9.prototype.Bf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
b9.prototype.yd=function(a){g.yZ.prototype.yd.call(this,a);this.A.Td("remote","currentReceiver",this.J[a]);this.D.Sb()};g.t(c9,g.UU);g.h=c9.prototype;g.h.create=function(){mFa(g.LN(g.Y(this.o)));this.F.push(g.hG("yt-remote-before-disconnect",this.hR,this));this.F.push(g.hG("yt-remote-connection-change",this.ZT,this));this.F.push(g.hG("yt-remote-receiver-availability-change",this.qD,this));this.F.push(g.hG("yt-remote-auto-connect",this.VT,this));this.F.push(g.hG("yt-remote-receiver-resumed",this.UT,this));this.qD()};
g.h.load=function(){this.o.yu();g.UU.prototype.load.call(this);this.D=new V8(this,this.o,this.A);var a=(a=rFa())?a.currentTime:0;var b=T8()?new p8(O8(),void 0):null;0==a&&b&&(a=l8(q8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));uFa(this,this.G,this.G);g.W_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.hf(this.D,this.A);this.A=this.D=null;g.UU.prototype.unload.call(this);g.W_(this.o.app,5)};
g.h.X=function(){g.iG(this.F);g.UU.prototype.X.call(this)};
g.h.ym=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.RB.apply(this.D,[a].concat(g.oa(c)))};
g.h.gK=function(){return this.loaded?this.D.suggestion:null};
g.h.dg=function(){return this.A?q8(this.A).dg:!1};
g.h.hasNext=function(){return this.A?q8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.YO=function(){var a=q8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.kd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+j8(a):a.C,isPeggedToLive:1>=(a.F?a.B+j8(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+j8(a):a.B,seekableStart:0<a.D?a.D+j8(a):a.D}};
g.h.ZO=function(){this.A&&this.A.MF()};
g.h.aP=function(){this.A&&this.A.NF()};
g.h.hR=function(a){1==a&&(this.K=this.A?q8(this.A):null)};
g.h.ZT=function(){var a=T8()?new p8(O8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.gf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.wB(a.videoId,l8(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.qD=function(){this.H=[this.B].concat(oFa());var a=P8()||this.B;d9(this,a);this.o.xa("onMdxReceiversChange")};
g.h.VT=function(){var a=P8();d9(this,a)};
g.h.UT=function(){this.C=P8()};
g.h.XO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?f8():d9(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&f8(),!0):!1}};
g.h.bP=function(){u8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Cc=function(){return!1};g.LX.remote=c9;})(_yt_player);
